### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by jlripoll** [slush0/stratum-mining#6]
hello people I have the following problem ...
Thanks x help :)

jlripoll@ubuntuServer:~/stratum-mining-master/litecoin_scrypt$ twistd -ny launcher_demo.tac
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 451, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 462, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 203, in loadValueFromFile
    fileObj = open(filename, mode)
exceptions.IOError: [Errno 2] No such file or directory: 'launcher_demo.tac'

Failed to load application: [Errno 2] No such file or directory: 'launcher_demo.tac'

**Comment by slush0** [comment]
> litecoin_scrypt

You're obviously using another fork of this repo as this code handle only bitcoin/sha256
